title: Gidon Kaminer
description: Thoughts and projects. nothing on this site is LLM generated. Any mistakes are my own. To correct any mistakes I've made, please email gidon (dot) kaminer (at) gmail (dot) com.
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme